### ISSUE TITLE
Json files not being put in with the compiled code

### ISSUE THREAD

**Issue by Will-Smith11** [proximacapital/gulp-tasks#24]
### Brief:
when running gulp build. we end up excluding  .json files from the compiled files. this causes errors when we try to run a program and read config

![image](https://user-images.githubusercontent.com/44074786/162849346-37d77e07-0cc9-4536-ab8a-cf3225c3198d.png)

### Scope:
update the gulp build task to include .josn files with compiled code

**Comment by stevenpollack** [comment]
We're not using `gulp-tasks` yet, are we?

**Comment by stevenpollack** [comment]
so the issue here isn't that the gulp file doesn't copy config files, it's that the structure of basis-arb isn't correct. The `Config/` directory should be top-level, not nestled in source. If you look at the `Copy.ts` task you'll see that we do move the contents of `Config/`, but in the basis-arb case, `Config/` doesn't exist, `Src/Config/` does.

**Comment by stevenpollack** [comment]
see https://github.com/proximacapital/gulp-tasks/blob/prod/Src/Tasks/Copy.ts#L13-L18

**Comment by stevenpollack** [comment]
Another option, if you don't want to rearrange the folder structure, is you can add those particular JSON files to the `tsconfig.json` file...

**Comment by Will-Smith11** [comment]
I'll just remove the nested config
